{% set name = "anaconda-cloud-auth" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud_auth-{{ version }}.tar.gz
  sha256: d9e2a0c4a9be478060d33950ff1aa4186c43ad901a112944cdbaac4951c1d45b

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs >=0.3
    - pip
  run:
    - python
    - keyring
    - pkce
    - python-dotenv
    - pydantic
    - pyjwt
    - requests
    - cryptography >=3.4.0
    - semver
test:
  imports:
    - anaconda_cloud_auth
  commands:
    - pip check
    - python -c "from anaconda_cloud_auth import __version__; assert __version__ == \"{{ version }}\""
  requires:
    - pip

about:
  summary: A client auth library for Anaconda.cloud APIs
  description: |
    A client library for Anaconda.cloud APIs to authenticate and securely store API keys.
    This package also provides a requests client class that handles loading the API key 
    for requests made to Anaconda Cloud services.
  home: https://anaconda.cloud
  doc_url: https://pypi.org/project/anaconda-cloud-auth/
  dev_url: https://pypi.org/project/anaconda-cloud-auth/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
