{% set name = "anaconda-cloud-auth" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud_auth-{{ version }}.tar.gz
  sha256: ff61aab300fa174a4ee02578e22be81ee1e093a9aa75d835e232130ac75894df

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  # trigger

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python
    - keyring
    - pkce
    - python-dotenv
    - pydantic <2.0
    - pyjwt
    - requests
    - cryptography >=3.4.0
    - semver <3
    - pywin32-ctypes 0.2.2  # [win]

test:
  imports:
    - anaconda_cloud_auth
  commands:
    - pip check
    - python -c "from anaconda_cloud_auth import __version__; assert __version__ == \"{{ version }}\""
  requires:
    - pip

about:
  summary: A client auth library for Anaconda.cloud APIs
  description: |
    A client library for Anaconda.cloud APIs to authenticate & securely store API keys.
    This package also provides a requests client class that handles loading the API key 
    for requests made to Anaconda Cloud services.
  home: https://anaconda.cloud
  doc_url: https://pypi.org/project/anaconda-cloud-auth/
  dev_url: https://pypi.org/project/anaconda-cloud-auth/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
